"""adiciona campo tipo no usuario

Revision ID: 7896e185fbe6
Revises: df5601e227d0
Create Date: 2026-06-19 19:39:14.917567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7896e185fbe6'
down_revision = 'df5601e227d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
